name: Minor Drafter
on:
  push:
    branches:
      - develop
jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: minor-drafter-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.DRAFTER_TOKEN }}